# =========================
# Terminal foot config
# =========================

# =========================
# Theme
# =========================
include=~/.config/foot/themes/catppuccin-mocha.ini

[main]
font=JetBrainsMono Nerd Font:size=12
font-bold=JetBrainsMono Nerd Font:style=Bold:size=12
font-italic=JetBrainsMono Nerd Font:style=Italic:size=12
font-bold-italic=JetBrainsMono Nerd Font:style=Bold Italic:size=12

# fallback pour emojis / symboles
font-fallback=Noto Color Emoji

bold-text-in-bright=no

title=foot
csd preferred=no

letter-spacing=0
dpi-aware=no
initial-window-size-pixels=700x500 
pad=25x25 center

# Scrollback
scrollback-lines=10000

# =========================
# Cursor
# =========================
[cursor]
style=beam
blink=yes
beam-thickness=1.5
blink-rate = 500

# =========================
# Mouse
# =========================
[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes
scrollback-up-mouse=BTN_WHEEL_BACK
scrollback-down-mouse=BTN_WHEEL_FORWARD

# =========================
# Key bindings
# =========================
[key-bindings]

# Scroll
scrollback-up-page=Shift+Page_Up Shift+KP_Page_Up
scrollback-down-page=Shift+Page_Down Shift+KP_Page_Down

# Clipboard
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste

# Font size
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

# Search
search-start=Control+Shift+r
find-prev=Control+r
find-next=Control+s

# Cursor movement
cursor-left=Left Control+b
cursor-left-word=Control+Left Mod1+b
cursor-right=Right Control+f
cursor-right-word=Control+Right Mod1+f
cursor-home=Home Control+a
cursor-end=End Control+e
delete-prev=BackSpace
delete-prev-word=Mod1+BackSpace Control+BackSpace
delete-next=Delete
delete-next-word=Mod1+d Control+Delete

# =========================
# URL detection
# =========================
[url]
launch=xdg-open ${url}
osc8-underline=url-mode

# =========================
# Bell
# =========================
[bell]
urgent=no
notify=yes

# =========================
# Special keys
# =========================
[text-bindings]
# \x03=Mod4+c  # Map Super+c -> Ctrl+c